Add Ghostty support & fixes
jamestalmage/supports-hyperlinks pull request #26
Opened 2024-12-27 08:17 UTC by LitoMore

### Changes

- Add Ghostty support
- Fix failing XO tests
- Add missing unit tests
- Ignore the `complexity` warning since we will keep adding more and more conditions to the function
- Upgrade to `nyc@15` for fixing coverage reports

2024-12-27 13:01 UTC, illright requested changes

2024-12-27 13:01 UTC, illright commented on index.js
> +				return version.major >= 1 && version.minor >= 72;
issue: this might cause the detection to fail for VS Code 2.0 (if it ever happens):
- `version.major === 2` (>= 1)
- `version.minor === 0` (< 72)

suggestion: I think that was the reason for the original separated condition, so I suggest we bring it back

2024-12-27 13:01 UTC, illright commented on index.js
> +			case 'ghostty':
high five for ghostty tho :)

2024-12-27 13:14 UTC, LitoMore commented on index.js
> +				return version.major >= 1 && version.minor >= 72;
Ah, I almost overlooked that.

Thank you for pointing out.

2024-12-30 00:29 UTC, illright approved these changes

2025-02-02 06:20 UTC, merged

2025-02-02 06:58 UTC, sindresorhus commented
https://github.com/chalk/supports-hyperlinks/releases/tag/v3.2.0